// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config } from "dotenv";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

config({ path: resolve(import.meta.dirname, "../../.env") });

const directDbUrl = process.env["DIRECT_URL"];

if (!directDbUrl) {
  throw new Error("DIRECT_URL is missing in the environment");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: directDbUrl,
  },
});
